= Class
:toc:

== Context in Semantic Analysis

All properties must be declared into the current scope, even though they are also declared with their owner separately. This is to allow differentiation among properties, constructor parameters and local variables.

== Primary Constructor Parameters
Due to the behaviour in Kotlin (as of Kotlin 1.9) that primary constructor parameters have higher precedence than member instances, an additional inner scope is introduced to declare constructor parameters. This introduction introduces inconsistency in replaced variable names, so non-property constructor parameters will be copied with a different variable name in the inner scope.

Also, note that member properties declared in primary constructor are immutable in default value expressions, even if these properties are marked as `var`. For example, the following code is invalid:
```
class Cls(var a: Int = 60, var b: Int = a++)
```

And this is valid:
```
class Cls(var a: Int = 60) {
    var b: Int = a++
}
```

== Variable scope / "transformedRefName"

Using `"${declaredName}/${scopeLevel}"` as `transformedRefName` is not safe, because `scopeLevel` can clash when extension functions come in. So, a unique index is generated for `transformedRefName`.

== The "this" keyword

Two variables, `this` and `this/${className}`, are defined. The second one is to cater cases like this:

[source, kotlin]
....
class B(var a: Int) {
    fun inc(x: Int) {
        a += x
    }
}
class A(val b: B, var c: Int) {
    fun addC(): Int {
        return c++
    }

    fun B.f() {
        inc(addC()) // <1>
    }

    fun a() {
        b.f()
    }
}
....

<1> `this` of the function call `addC()` belongs to class `A`, while `this` of the function call `inc()` refers to class `B`.

== The "super" keyword

A hack is implemented in Interpreter to resolve the "super" keyword. The "super" variable resolves to the "this" instance. While evaluating `NavigationNode`, get the actual class name of "super", that was resolved properly in Semantic Analyzer, and lookup `parentInstance` of the "this" instance until reaching the actual class of "super". Both read and write operations have this hack implemented.

== Abstract Classes

As only abstract functions are supported, the only things need to be implemented are:

- Parse 'abstract' modifier in Parser
- Parser does not parse function body if 'abstract' modifier applies
- Implement modifier checks in Semantic Analyzer
- Disallow calling abstract functions directly via `super.abstractFunction()` expressions in Semantic Analyzer
- Throw exception in Interceptor if a direct call is made to an abstract function, which supposes to be avoided by Semantic Analyzer

== Dealing with `<T : Comparable<T>>`

Note there is a recursion in this definition. This creates an infinite loop to `isAssignableFrom()` and `superTypeOf()`.

For `isAssignableFrom()`, a special data type `RepeatedType` and a data structure `SymbolTableTypeVisitCache` are introduced. Type `RepeatedType` holds a field `actualType`. Whenever a type is about to be visited, it is added to `SymbolTableTypeVisitCache` (pre-visit). When a type finishes visiting, the result is recorded to `SymbolTableTypeVisitCache` (post-visit). If a type is visited before post-visit, then `RepeatedType` would be returned and registered into `SymbolTableTypeVisitCache`. In post-visit, the result is propagated to the field `actualType` of all the registered `RepeatedType` instances.

In some cases where an ad-hoc call of `assertToDataType` is needed, `SymbolTableTypeVisitCache` is copied to prevent polluting the cache.

It is also tricky to resolve a function definition like this:
....
fun <T : Comparable<T>> List<T?>.binarySearch(
    element: T?,
    fromIndex: Int = 0,
    toIndex: Int = size,
): Int
....

When a type parameter is present, they are all added to `SymbolTableTypeVisitCache` before start visiting, otherwise the type parameter cannot be resolved.

While resolving function declarations, the field `actualType` of `RepeatedType` is never filled. In this case, it would be treated as an "Any" type with nullability same as that in the declaration.

For `superTypeOf()`, Kotlite follows the same handling with Kotlin 1.9. That is, for Int and String, where Int : Comparable<Int> and String : Comparable<String>, their super type is Comparable<*>. So, if a repeated type is encountered, a star type is returned.
