name: Verification Tests
on:
  push:
    branches:
      - '**'

concurrency:
  group: "tests-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: ./gradlew check -PCICD=GitHubActions # the "clean" task would fail on GitHub Actions: https://github.com/sunny-chung/kdatetime-multiplatform/actions/runs/8213856523/job/22465724399
      - uses: actions/upload-artifact@v3
        with:
          name: test-result_${{ matrix.os }}_interpreter
          path: interpreter/build/reports/tests
        if: ${{ !cancelled() }}
      - uses: actions/upload-artifact@v3
        with:
          name: test-result_${{ matrix.os }}_stdlib
          path: stdlib/build/reports/tests
        if: ${{ !cancelled() }}
